name: Build example project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    - name: Checkout zig-string
      uses: actions/checkout@v4
      with:
        repository: 'JakubSzark/zig-string'
        ref: 'f6f9e5dc7c5c45a72473de245a0e6958ef2bf913'
        path: src/zig-string
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.15.1
    
    - name: Build example project (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        #!/bin/bash
        export ORNG_STD_PATH="$GITHUB_WORKSPACE/std"
        export ORNG_BUILTIN_PATH="$GITHUB_WORKSPACE/src/hierarchy/builtin.orng"
        zig build orng
        cd examples
        ../zig-out/bin/orng build
    
    - name: Build example project (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        #!/bin/bash
        export ORNG_STD_PATH="$GITHUB_WORKSPACE/std"
        export ORNG_BUILTIN_PATH="$GITHUB_WORKSPACE/src/hierarchy/builtin.orng"
        zig build orng
        cd examples
        ../zig-out/bin/orng build

    # Optional: Upload artifacts if build fails
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: zig-cache/log
